### ISSUE TITLE
Azure Pipeline: pact-core@13.15.0: Failed to initialise native module for linux-x64

### ISSUE THREAD

**Issue by fej** [pact-foundation/pact-js-core#458] opened 2023-07-08 08:18 UTC
Hi, 

I've error when run pipeline on Microsoft Azure with this message:
pact-core@13.15.0: Failed to initialise native module for linux-x64: Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.16.1

In package.json there is line "@pact-foundation/pact": "10.4.1" 

Thanks,
FEj

**Comment by YOU54F** [comment] 2023-07-08 10:18
hey

1. have you had this working prior or is this a new setup
2. are your tests working? 13.15.0 had an issue whereby the message was always present, but not an error, it’s suppressed in v14 unless we completely can’t find any bindings on any path

**Comment by TimothyJones** [comment] 2023-07-08 12:19
Additionally, do you see any errors on a clean install (remove `node_modules` and `package-lock.json`)

Beyond that, there should have been an issue checklist - please attach the following information:

- **OS**: _e.g. Mac OSX 10.11.5_
- **Pact Node version**: _e.g. Pact Node v2.6.0_
- **Node Version**: `node --version`
- **Other Versions**: _Any other versions you think might be relevant (optional)_

### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file

**Comment by YOU54F** [comment] 2023-07-10 16:40
so v10 and v11 of pact-js

https://www.npmjs.com/package/@pact-foundation/pact/v/10.4.1?activeTab=code

    `"@pact-foundation/pact-core": "^13.13.3",`


it uses a caret

```
  ~version "Approximately equivalent to version" See [semver](https://github.com/npm/node-semver#versions)
  ^version "Compatible with version" See [semver](https://github.com/npm/node-semver#versions)
```

which means it will pick up minor versions, so `13.15.0` gets picked up for the prebuilds from v10/v11 of pact-js

Deprecating `13.15.0` of pact-js-core in npm will mean it wont get picked up, on an npm install of pact-js.

Pact-js-core is tightly coupled with its ffi library and bindings, I wonder if its loose enough across the boundary to pact-js for this to be a non issue, or if we should actually be limiting to `~` so we only pick up patches.

good note here

https://stackoverflow.com/a/22345808

**Comment by YOU54F** [comment] 2023-07-10 16:54
I've deprecated `13.15.0` now

https://www.npmjs.com/package/@pact-foundation/pact-core/v/13.15.0?activeTab=versions so the prebuild binaries will be opt-in with pact-js 12.x and pact-core 14.x

**Comment by mefellows** [comment] 2023-07-10 22:23
The caret semver was by design - new features, bug fixes etc. should be able to be released in the core and land in Pact JS without impacting Pact JS, as minor enhancements should be backwards compatible. The downside is a bug introduced into a minor version will make it's way into new Pact installs or dependency updates.

**Comment by YOU54F** [comment] 2023-07-11 17:33
Hey @fej are you able to retest?

**Closed** 2023-08-03 13:57 UTC
Labels: bug
